apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: cni
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  values:
    profile: ambient
    cni:
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
      cniBinDir: /var/lib/rancher/k3s/data/cni
    cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
    cniBinDir: /var/lib/rancher/k3s/data/cni