apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: gateway
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  values:
    name: istio-ingress
    namespace: istio-system
    service:
      type: NodePort
      ports:
        - name: http2
          nodePort: 80
          protocol: TCP
          targetPort: 80
          port: 80
        - name: https
          nodePort: 443
          protocol: TCP
          targetPort: 443
          port: 443
        - name: status-port
          port: 16021
          protocol: TCP
          targetPort: 15021