apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base.yaml
- ingress.yaml
- istiod.yaml
- namespace.yaml
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0-rc.1/standard-install.yaml
- istio-metrics.yaml
- gateway.yaml
- cross-net-gateway.yaml
labels:
- pairs:
    toolkit.fluxcd.io/tenant: sre-team
