apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base.yaml
- cni.yaml
- ingress.yaml
- istiod.yaml
- ztunnel.yaml
- namespace.yaml
labels:
- pairs:
    toolkit.fluxcd.io/tenant: sre-team
