apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m0s
  url: https://istio-release.storage.googleapis.com/charts