apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
spec:
  interval: 60m
  chart:
    spec:
      chart: kiali-server
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kali
      interval: 12h
  values:
    deployment:
      pod_annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
#    auth:
#      strategy: "openid"
#      openid:
#        client_id: "kiali-client"
#        disable_rbac: true
#        issuer_uri: "https://keycloak.auth.apoorva64.com/realms/lab"
    external_services:
      prometheus:
        url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"